- .github/workflows/auto-assign.yaml
- close: #30 
- 設定ミスがあれば教えてください
- すでに `vars.REVIEWERS` には値が入るように設定しています
- チームをレビュアーに設定できるようにすることも検討しましたが、特殊な権限のトークンが必要になり手間が増えてしまうため、テンプレートプロジェクトでは設定しないようにしました
- 外部からのプルリクエスト時にも動作するように `pull_request_target` で起動することも検討しましたが、現状のアプリ開発ではコードを公開することがないため、いったん `pull_request` で起動するようにしました。
特にありません。
> プルリクエスト提出時の自動アサインワークフロー作成

- docs/GET_STARTED.md
- 開発において必要な内容をGET_STARTED.mdに記載しました。
- 署名Commitができていなかったので再度作り直しました
チケット
- close #40 
- こちらから`GET_STARTED.md`が確認できます。
https://github.com/yumemi-inc/flutter-mobile-project-template/blob/7dc9a14f2221cd0db92780ff617aba0e5c449ca8/docs/GET_STARTED.md
> 開発において必要な内容をGET_STARTED.mdに記載 

- .gitignore
> refactor: .gitignoreのmason指定範囲を最小限にする

- packages/cores/designsystem/lib/src/themes/bottom_navigation_bar_theme.dart
- packages/cores/designsystem/lib/src/themes/theme.dart
> [!NOTE]
> 今回の PR で該当 Issue タスクとしては完了といたします 。
> Space などの定義が必要になった場合は別途 Issue を作成する予定です。
- close #22
#67 に加えてもう一つサンプルとして cores_designsystem パッケージに BottomNavigationBar のテーマ定義を追加します。
- このテンプレートを利用する際に、ドキュメントやコメントで使い方が把握できそうかご確認いただきたいです
> feat(designsystem): BottomNavigationBar のテーマを追加

- apps/app/lib/main.dart
- apps/app/pubspec.lock
- apps/app/pubspec.yaml
- packages/cores/core/build.yaml
- packages/cores/core/lib/src/exception/app_exception.dart
- packages/cores/core/lib/src/exception/index.dart
- packages/cores/core/lib/src/exception/provider/app_exception_notifier_provider.dart
- packages/cores/core/lib/src/exception/provider/app_exception_notifier_provider.g.dart
- packages/cores/core/lib/src/ui/index.dart
- packages/cores/core/lib/src/ui/util/snack_bar_manager.dart
- packages/cores/core/lib/ui.dart
- packages/cores/core/pubspec.yaml
- packages/cores/data/lib/src/network/provider/dio.dart
- packages/cores/data/lib/src/network/provider/dio.g.dart
- packages/features/debug_mode/lib/src/data/api/provider/exception_generator_api.dart
- packages/features/debug_mode/lib/src/data/api/provider/exception_generator_api.g.dart
- packages/features/debug_mode/lib/src/ui/debug_mode_page.dart
> [!NOTE]
> 本 PR は　feat: エラーハンドリングを追加する - デバッグモードパッケージを追加する #82 の続きです。
closes #23 
本 PR では以下の実装を行っています。
- ボタン押下時に何かしらの例外が発生するようにする
- 外部との HTTP 通信で発生したエラー DioException を独自の例外に変換するようにする
- アプリ内で定義した独自の例外を管理する provider （以下、appExceptionProvider）を用意する
- App で appExceptionProvider を購読する処理を実装する
- 例外を受信した際に、スナックバーのようなものが常時表示されるようにする
- AppExceptionNotifier: アプリ内で定義した独自例外 AppException を管理する provider
- apps/app: AppExceptionNotifier を listen する
- packages/cores/core: AppExceptionNotifier を定義する
- packages/features/xxx: AppException を補足時に、AppExceptionNotifier に通知する(notify) 
apps/app ---> packages/cores/core <---- packages/features/xxx
- 設計に違和感はないか
<video src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/54063249/3d46c2b8-19ad-421d-b9c6-bb791935586f" width="300" />
1. アプリを起動する
2. …
> feat: エラーハンドリングを追加する - アプリ内で例外補足時にスナックバーを表示する

- melos.yaml
close #87 
本 issue の [こちらのコメント](https://github.com/yumemi-inc/flutter-mobile-project-template/issues/87#issuecomment-1907497672) をご確認ください。
- concurrency（同時に並列実行されるパッケージ数）の 1 つにしていた制限をデフォルトの 5 に変更した後も、`generate_code` ステップが問題なく成功しているか
- ローカル環境および GitHub Actions 内で 5 回施行する限り、すべて正常に動作していることを確認しています。
```bash
melos run regenerate_code
└> melos exec --concurrency 1 --order-dependents -- "dart run build_runner build -d"
└> RUNNING
$ melos exec
└> dart run build_runner build -d
└> RUNNING (in 5 packages)
--------------------------------------------------------------------------------
cores_core:
[INFO] Generating build script...
[INFO] Generating build script completed, took 154ms
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 54ms …
```
> feat: melos exec から concurrency オプションを削除する

- packages/cores/core/analysis_options.yaml
cores/core パッケージの `analysis_options.yaml` に custom_lint の記載が漏れていたため追記しました。
記載に不備がないか
不要
<!--
不要
> cores/core パッケージの custom_lint の記載漏れ対応

- tools/bricks/cores_package_dart/LICENSE
- tools/bricks/cores_package_flutter/LICENSE
- close: #100 
不要なLICENSEファイルが残っていないか確認してください。
プロジェクトルートにあるLICENSEファイルは必要なので残しています。
スキップ
IDEのファイル検索機能などでLICENSEファイルを探してください
コンフリクトする可能性があるため`fix/bricks-package-name`ブランチからこのブランチを作成し、マージ先に指定しています。
このPRは`fix/bricks-package-name`のマージ後に`main`ブランチにマージします。
> LICENSEファイルを削除する

- apps/app/pubspec.lock
- apps/app/pubspec.yaml
- apps/catalog/pubspec.lock
- apps/catalog/pubspec.yaml
- packages/cores/core/pubspec.yaml
- packages/cores/data/pubspec.yaml
- packages/cores/designsystem/pubspec.yaml
- packages/cores/init/pubspec.yaml
- packages/features/debug_mode/pubspec.yaml
- packages/features/github_repository/pubspec.yaml
- tools/bricks/cores_package_dart/__brick__/packages/cores/{{package_name.snakeCase()}}/CHANGELOG.md
- tools/bricks/cores_package_dart/__brick__/packages/cores/{{package_name.snakeCase()}}/pubspec.yaml
- tools/bricks/cores_package_flutter/__brick__/packages/cores/{{package_name.snakeCase()}}/CHANGELOG.md
- close: #101 
- 実パッケージに合わせて、Brickテンプレートから`CANGELOG.md`を削除
バージョンが0.0.1以外のパッケージが存在しないかを確認してください
スキップ
IDEの文字検索機能などを活用してパッケージバージョンを探してください
コンフリクトの可能性があるため、`fix/#100`ブランチからこのブランチを作成し、マージ先に指定しています。
このPRは`fix/#100`のマージ後、`main`ブランチにマージされます。
> パッケージバージョンを0.0.1に統一する

- apps/app/pubspec.lock
- apps/app/pubspec.yaml
- packages/cores/core/lib/src/app_status/model/app_status.freezed.dart
- packages/cores/core/lib/src/app_status/model/force_update_status.freezed.dart
- packages/cores/core/lib/src/app_status/model/force_update_target_version.freezed.dart
- packages/cores/core/lib/src/app_status/model/maintenance_mode_status.freezed.dart
- packages/cores/core/pubspec.yaml
- packages/features/github_repository/lib/src/domain/model/github_repository.freezed.dart
- packages/features/github_repository/pubspec.yaml
- close: #121 
- freezed の差分で CI が落ちるという事象が発生していました。
- それを解決するために freezed のバージョンを v2.4.7 に更新しました。（原因につきましては Issue を参照していただければと思います）
- バージョン更新漏れがないか
なし
なし
なし
> freezed のバージョンを v2.4.7 に更新する

- .gitattributes
- apps/app/lib/feature/home/ui/home_page.dart
- apps/app/pubspec.lock
- apps/catalog/pubspec.lock
- packages/cores/designsystem/lib/src/theme_extensions/app_colors/app_colors.dart
- packages/cores/designsystem/lib/src/theme_extensions/app_colors/app_colors.g.theme.dart
- packages/cores/designsystem/lib/src/theme_extensions/app_colors/index.dart
- packages/cores/designsystem/lib/src/theme_extensions/index.dart
- packages/cores/designsystem/lib/src/themes/theme.dart
- packages/cores/designsystem/lib/theme_extensions.dart
- packages/cores/designsystem/pubspec.yaml
close: #36 
- ThemeExtension を取り入れる上で考慮漏れがないか
- [theme_extensions_builder](https://pub.dev/packages/theme_extensions_builder)の導入が適切か
- メリット
- `copyWith`,`lerp`を自前実装する手間が減る
- `BuildContext`から ThemeExtension を取得する実装も含んでいる
- 懸念点
- build.yaml に自動生成の設定ができないため、生成対象範囲を絞ることができない
|           Android           |           iOS            |
| <video src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/89247188/dbf2bbf4-f71f-4137-bf03-89f54f549022" width="300" /> | <video src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/89247188/a899ea7f-5361-424f-bff9-37e0ff0787ae" width="300" /> |
- ホームページで歯車アイコンを押下し、設定画面を開く
- Theme を変更する
- ホームページに戻り、アイコンの色が変更されているかを確認する
> アプリ独自のカラーシステムを追加

- apps/catalog/lib/main.dart
close #118 
- デバイスフレームの種類が必要十分か
|           Before           |           After            |
| <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/23146955/f6c9b36c-9fbd-4395-859b-2030edbb9b59" width="300" /> | <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/23146955/e733f9c8-8238-44fb-aaec-eff1e8d33051" width="300" /> |
1. ui-catalog をビルドする
2. Addons -> device からデバイスフレームが追加されていることを確認する
or https://github.com/yumemi-inc/flutter-mobile-project-template/pull/130#issuecomment-1941021394 から確認できる
特になし
> UI Catalog に Android, tablet のデバイスフレームを追加

- docs/GET_STARTED.md
- close: #115
英語が正しいかどうか確認お願いします。
スキップ
スキップ
スキップ
> docs: Update GET_STARTED.md for fvm

- packages/features/setting/assets/l10n/app_en.arb
- packages/features/setting/assets/l10n/app_ja.arb
- packages/features/setting/lib/src/gen/l10n/l10n.dart
- packages/features/setting/lib/src/gen/l10n/l10n_en.dart
- packages/features/setting/lib/src/gen/l10n/l10n_ja.dart
- packages/features/setting/lib/src/ui/setting_page.dart
> [!NOTE]
> 継続でライセンスやアプリバージョンを追加する作業を実施予定です
- #116
ライセンスやアプリバージョンを追加するため、事前に設定画面の実装方法を ListView から CustomScrollView に変更します。
ライセンスやアプリバージョンは SliverList を追加することで対応しようと考えています。
- 実装に違和感がないかご確認いただきたいです
|           Before           |           After            |
| <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/19267812/a209c6c7-b58a-4ae4-aef8-e7912d5e1c1f" width="400" /> | <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/19267812/73348e9f-35e8-4425-bc8a-764b3cacc836" width="400" /> ||
> refactor(setting): 設定画面の実装方法を ListView から CustomScrollView に変更

- .github/ISSUE_TEMPLATE/improve.yml
- close: #142 
改善に必要な情報が過不足ないかをご確認ください（主観で大丈夫です）
スキップ
スキップ
issueにhttps://github.com/yumemi-inc/flutter-yumemi-lints/blob/main/.github/ISSUE_TEMPLATE/improve.yaml?plain=1 を参考にすると書いてありましたが、勝手な判断で現状のように変更しています。
> chore: 改善リクエストのためのissueテンプレートを追加する

- pubspec.lock
- pubspec.yaml
- close: #150
melos のバージョンを 3.4.0 -> 4.1.0 に変更します。
- CI が正常に終了することをご確認いただきたいです
> chore(deps): melos 3.4.0 -> 4.1.0

- .github/actions/cleanup-copilot-settings/action.yaml
- .github/actions/create-issue-at-initialization/action.yaml
- .github/workflows/auto-assign.yaml
- .github/workflows/check-diff.yaml
- .github/workflows/check-pr.yaml
- .github/workflows/template-cleanup.yaml
- docs/initialization/GITHUB_AUTO_ASSIGNMENT.md
- close: #148
GitHub Action を commit hash を利用した指定に変更します。
- コミットハッシュに切り替わっているかご確認いただきたいです
> [!NOTE]
> 詳しく確認する場合の例を示します。
> より簡単な方法があれば教えていただけると幸いです 🙏
> 1. 該当リリース or タグのページに移動
> 例: https://github.com/actions/setup-node/releases/tag/v4.0.2
> 2. コミットハッシュを選択
> ![CleanShot 2024-02-27 at 16 52 58@2x](https://github.com/yumemi-inc/flutter-mobile-project-template/assets/19267812/7e0e977f-95b7-4009-bebc-82c3f0d86465)
> 3. URL から完全なコミットハッシュを確認
> ![CleanShot 2024-02-27 at 16 55 02@2x](https://github.com/yumemi-inc/flutter-mobile-project-template/assets/19267812/1e21e128-74c6-4b58-9f46-7e17d13463aa)
| <img src="" width="300" /> …
> ci: GitHub Action を commit hash を利用した指定に変更

- removal_list_on_use_template.txt
`removal_list_on_use_template.txt`内のPathが間違っていたので修正する
軽微な修正なのでいissueは作成していません。
Pathが正しいかご確認ください
スキップ
スキップ
スキップ
> ci: `removal_list_on_use_template.txt`内のPathが間違っていたので修正する

- .github/actions/setup-application-runtime/action.yaml
- .github/workflows/check-diff.yaml
- .github/workflows/check-pr.yaml
- .github/workflows/firebase-hosting-pull-request.yaml
- close: #149 
カスタムアクションの命名が適切かレビューお願いします。
スキップ
このPRのCIがすでに適応されている状態になっているので、ご確認ください。
issue #149 に 「checkoutもSetupに含めた方が良いかも」とありましたが、GithubのCustom Actionを呼び出す前にcheckoutする必要があるのでSetupから除外しています。
含めると失敗することが以下でわかります。
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/8109139311/job/22163711914
> Improve/standardize setup for GitHub Actions workflow

- .github/actions/setup-application-runtime/action.yaml
- docs/GET_STARTED.md
- pubspec.lock
> [!NOTE]
> - ~~#156 の`main`へのマージ待ち~~
> ~~(#156のベースブランチから、本ベースブランチを切っています)~~
>   - 既にマージ済み
- close: #147
- GitHub Actionsが正常に動くかどうか
- READMEの英語部分、おかしなところ・違和感ありましたら 教えて下さい🙏
> GitHub Actionsのワークフローで 適切なmelosバージョンを利用するよう修正

- packages/features/setting/assets/l10n/app_en.arb
- packages/features/setting/assets/l10n/app_ja.arb
- packages/features/setting/lib/src/gen/l10n/l10n.dart
- packages/features/setting/lib/src/gen/l10n/l10n_en.dart
- packages/features/setting/lib/src/gen/l10n/l10n_ja.dart
- packages/features/setting/lib/src/ui/setting_page.dart
- packages/features/setting/pubspec.lock
- packages/features/setting/pubspec.yaml
- close #116
設定画面にアプリバージョンの表示を追加します．
- 実装に違和感がないかご確認いただきたいです
- 設定画面にアプリバージョンの項目が追加されます
|           Before           |           After            |
| <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/19267812/2fff5115-937d-4d35-99a5-98b4a549d982" width="400" /> | <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/19267812/212347c6-5310-47ae-a90f-f95f1951c3f6" width="400" /> |
1. アプリを起動
2. ホーム画面右上の歯車マークから設定画面に遷移
3. 設定画面上にアプリバージョン項目があることを確認
> feat(setting): アプリバージョン項目を追加

- .github/workflows/check-diff.yaml
- .github/workflows/check-pr.yaml
- .github/workflows/firebase-hosting-pull-request.yaml
- README.md
close: #152 
- GitHub ActionsのWorkflowに実行条件を追加し、不要な実行を削減します
- 実行条件はPR差分で十分かどうか
- 他のWorkflowにはつけなくてよいか
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)
> CIの実行条件を追加

- apps/app/pubspec.lock
- apps/app/pubspec.yaml
- melos.yaml
- packages/cores/core/pubspec.lock
- packages/cores/core/pubspec.yaml
- packages/cores/data/pubspec.lock
- packages/cores/data/pubspec.yaml
- packages/cores/init/pubspec.lock
- packages/cores/init/pubspec.yaml
- packages/cores/navigation/pubspec.lock
- packages/cores/navigation/pubspec.yaml
- packages/features/debug_mode/pubspec.lock
- packages/features/debug_mode/pubspec.yaml
- packages/features/github_repository/pubspec.lock
- packages/features/github_repository/pubspec.yaml
- packages/features/setting/pubspec.lock
- packages/features/setting/pubspec.yaml
close: #184 
- 考慮漏れがないか
動作に変更はありません。
動作に変更はありません。
> Riverpod を v2.5.1 に更新する

- .github/workflows/check-pr.yaml
Closes #182 
- 他に対応が必要なものはないか
アプリの挙動や見た目に影響する変更はないため省略
アプリの挙動や見た目に影響する変更はないため省略
> [Improve] dorny/paths-filter アクション部分を改善

- .github/actions/create-issue-at-initialization/action.yaml
- docs/initialization/RENAME_APPLICATION_ID.md
- scripts/rename-application-id.sh
- tools/rename-application-id.sh
close: #179
本 PR で対象とするアプリ ID 設定周りの変更箇所は、以下のコメントにまとめています。
https://github.com/yumemi-inc/flutter-mobile-project-template/issues/179#issuecomment-2062874553
- 期待されている処理が正常に実行されているか
- スクリプト内に怪しい箇所や考慮漏れしているところがないか
UI 上の変更はないため、スキップします。
以下の Markdown に記載された内容でローカル環境で実行してみてください。
https://github.com/yumemi-inc/flutter-mobile-project-template/compare/feature/179-implement-rename-application-id-tool?expand=1#diff-22ed6bde2623390ae1aa07ef45a9d539795b9f2d345987aaecd748297225aac8
```bash
bash-3.2$ pwd
/Users/k_kamashima/flutter-mobile-project-template/scripts
bash-3.2$ bash scripts/rename-application-id.sh "com.example.rename"
Starting application ID renaming process...
[Step1] Replacing the application ID definition in the configuration JSON files within the flavor directory...
Modifying file: …
```
> [Feature]: アプリ ID 設定についての Issue 自動生成とツールを開発する

- .github/actions/cleanup-copilot-settings/action.yaml
- .github/workflows/template-cleanup.yaml
close: #157
テンプレート機能を使用した際に実行される `Post Cleanup Copilot Settings` が以下のログとともに失敗します。
```bash
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/template-test/template-test/.github/actions/cleanup-copilot-settings'. Did you forget to run actions/checkout before running your local action?
```
本不具合と類似した issue のワークアラウンド対応を参考にして、`Cleanup Copilot Settings` の最後に `checkout` を実行してテンプレートプロジェクトのリポジトリにチェックアウトを実行して参照先を正す方法を試してみたいです。
> [!NOTE]
> 本修正対応は現環境での動作確認を行うことができません。
本 PR がメインにマージされた後、本テンプレートプロジェクトからリポジトリ作成した際の GitHub Action の結果を確認する必要があります。
- 対応方針に気になる点はないか？
| <img src="" width="300" /> | <img …
> [Bug]: テンプレート機能を使用した際の Action 失敗不具合を修正する

- .github/workflows/check-pr.yaml
- close #193
pre-check ジョブのスキップコメントが正常に動作していなかったため，正常に動作するよう修正します．
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/194#discussion_r1585911153 でも言及がありましたが，今後の保守性や拡張性を考慮して [peter-evans/create-or-update-comment](https://github.com/peter-evans/create-or-update-comment) を利用したプルリクエストコメント作成に変更します．
- 今回の PR では該当のワークフローのステップが走らない状態のため，変更箇所に違和感がないことをご確認いただきたいです
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/195#issuecomment-2088012921 でスキップコメントが正常に動作することを確認済みです 🙆
> [GH-193] peter-evans/create-or-update-comment を利用したプルリクエストコメント作成に変更

- .github/workflows/firebase-hosting-pull-request.yaml
- close: #197
- typo を修正しました。scrpts → scripts
- 他に似たような typo ないか
アプリの動作に影響ないため省略します。
アプリの動作に影響ないため省略します。
特になし
> fix: typo を修正

- apps/app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- apps/app/ios/scripts/extract_dart_defines.sh
- 元々のBuildのpre-actionsで使っていたスクリプトだと、Android Studioでのビルド時Flutterが自動定義する項目が含まれたままでiOSビルド失敗の原因となっていた。
- 具体的にはこれ
```
flutter.inspector.structuredErrors=true
```
- [こちらの記事](https://zenn.dev/altiveinc/articles/separating-environments-in-flutter#%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E4%BF%9D%E5%AD%98)を参考に必要なものだけ含むように修正
- VSCodeとAndroid StudioでiOSビルドできることを確認しました。
> Flutterが自動定義した項目が含まれることでAndroid Studioでビルドできないバグを修正

- apps/catalog/web/index.html
close #210
- index.htmlをFlutter 3.22で新規プロジェクトを作った時の形式に変更しました
- [これ](https://github.com/Zudah228/flutter_upgrade_demo/pull/1/files?w=1)がわかりやすい
- catalogが起動できることを確認しました
> refactor: catalogのindex.htmlをFlutter 3.22仕様に更新

- docs/initialization/README.md
- removal_list_on_use_template.txt
https://yumemi.slack.com/archives/C0585H2BG9L/p1717474880882099?thread_ts=1717383270.490549&cid=C0585H2BG9L
> add: 初期化時に削除するファイルにdocs/initializationを追加

- .github/workflows/check-pr.yaml
- melos.yaml
- tools/bricks/cores_package_flutter/__brick__/packages/cores/{{package_name.snakeCase()}}/pubspec.yaml
close #206 
- report_testスクリプトのpackageFiltersにtestを追加しました
- appとかはtestディレクトリがないので、testの依存だけ追加しても失敗しますがそれは正常な動作と思ってスルー
- test_report.logファイルが全く作成されないと、Report testステップでエラーになるのでファイルの存在チェックステップを追加
- Report testステップでpackages/coresとpackages/featuresのレポートファイルに反応してなかったのでglobを修正
- https://github.com/yumemi-inc/flutter-mobile-project-template/runs/25733329183
> add: testの依存があるパッケージだけreport_testスクリプトの対象にする

- apps/app/android/app/build.gradle
- apps/app/lib/app_build_config.dart
- packages/cores/core/lib/extension.dart
- packages/cores/core/lib/src/extension/enum.dart
close #227
close #228
devの時
```
I/flutter ( 5798): 👻 INFO 2024-06-04 17:46:41.159521 [package:flutter_app/app_initializer.dart 18:12 in AppInitializer.initialize] AppBuildConfig(appName: dev-Template, buildNumber: 1, packageName: jp.co.yumemi.template.dev, version: 0.0.1, buildSignature: D6EB1742B1D2C213BA74ED3A4A8EB5141844325E, flavor: Flavor.dev, installerStore: com.android.shell)
```
prdの時
```
I/flutter ( 5999): 👻 INFO 2024-06-04 17:47:26.821135 [package:flutter_app/app_initializer.dart 18:12 in AppInitializer.initialize] …
```
> dart-define系のissueを修正

- apps/app/lib/router/navigator/home_navigator.dart
- apps/app/lib/router/provider/router.g.dart
- apps/app/lib/router/routes/main/home/home_shell_branch.dart
- packages/cores/navigation/lib/src/home/navigator.dart
- packages/features/github_repository/lib/src/domain/model/github_repository.dart
- packages/features/github_repository/lib/src/domain/model/github_repository.freezed.dart
- packages/features/github_repository/lib/src/domain/model/github_repository.g.dart
- packages/features/github_repository/lib/src/ui/github_repository_detail_page.dart
- packages/features/github_repository/lib/src/ui/github_repository_list.dart
close: #260 
| <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/87256037/ca97ea69-a22f-4d1a-96ae-0b0974a755b0" width="300" /> | <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/87256037/4aa7d77a-b009-4776-b69a-28cf72808f50" width="300" /> | <img src="" width="300" /> |
> #260 GitHubリポジトリの詳細ページにdescriptionを追加

- apps/app/lib/main.dart
- packages/features/setting/lib/l10n.dart
- tools/bricks/features_package/__brick__/packages/features/{{feature_name.snakeCase()}}/lib/l10n.dart
https://yumemi.slack.com/archives/C0585H2BG9L/p1718689788300589?thread_ts=1718682025.912949&cid=C0585H2BG9L
- messageというfeatureを増やした時、以下のようになること
```
import 'package:features_message/src/gen/l10n/l10n.dart';
typedef MessageL10n = L10n;
```
> refactor: L10nをtypedefでexport

- docs/en/SPLASH_SCREEN.md
- docs/ja/SPLASH_SCREEN.md
[相談]
手順に環境ごと（prod,staging,dev）のスプラッシュ画面を用意するドキュメントを用意するか
個人的には、launcher_iconで環境ごとにアイコンを用意しているので、準備しなくていいのではと思っています。
close: #11 
issueのコメントより、
アプリによりスプラッシュ画面の実装はそれぞれなので、このテンプレートプロジェクトには実装はせず、スプラッシュ画面設定のドキュメントを作成する。
不自然な説明になっていないか。
> #11 splash画面実装のドキュメント準備する

- tools/bricks/features_package_core/hooks/post_gen.dart
close: #271
brickでfeatureを追加したときに以下の処理をするようにしました
- apps/appのdependencyに追加したfeatureの依存を追加
- apps/appのmain.dartでfeatureのL10nをMaterialAppに追加
- main.dartをdart formatしてるんですが、importのソートがかからないのは一旦スルーしてます
mason make features_packageもしくはmason make features_package_coreを実行する
> appで追加パッケージのl10nをMaterialAppに追加を自動化

- docs/ja/NEW_FEATURE.md
Featureパッケージ追加から画面遷移するまでの手順を作成しました。
- 文章書くのが下手なので、読みにくい場合は適宜指摘いただけますと幸いです。
Documentの通り実行して新たに作成されたFeatureパッケージに画面遷移できるか確認しました。
Documentの通り実行して新たに作成されたFeatureパッケージに画面遷移できるか確認する。
> 📝 Featureパッケージ追加から画面遷移するまでの手順を作成

- melos.yaml
- packages/cores/data/pubspec.lock
- packages/cores/data/pubspec.yaml
- packages/cores/data/test/cores_data_test.dart
- close: #287 
- dependsOn で or 条件で指定することができないため、スクリプトの数が増えてしまっているが、もっと適した方法はないか
- 期待通りに動作するか
> improve: melos の Dart/Flutter のテストコマンド用のスクリプトを改善

- .github/actions/cleanup-samples/action.yaml
- .github/actions/fill-project-name/action.yaml
- .github/workflows/initialization.yaml
- removal_list_on_use_template.txt
- close: #275
サンプル実装に関するクリーンアップワークフローの調整を実施します。
併せて、リポジトリ名反映のワークフローにスネークケース変換処理を追加します。
- 内容に過不足がないか
- https://github.com/tatsutakein/remove-samples-flutter-template-project/commit/ee16254bc14936e411cc075dfb7a8362e0afe788
> ci: サンプル実装に関するクリーンアップワークフローの調整

- apps/app/lib/main.dart
- apps/app/lib/router/routes/main/home/home_shell_branch.dart
- apps/app/lib/ui/home_page.dart
- close: #298
デバッグ画面への遷移をホーム画面上のアクションボタンタップから shift + d に変更します。
- コードに違和感がないか
- 内容に過不足がないか
https://github.com/user-attachments/assets/80c64021-b159-4723-81f8-c5bd5831a511
1. アプリをエミュレータ / シミュレータで起動
2. パソコンのキーボードで shift + d を押下してデバッグ画面に遷移すること
> feat(app): デバッグ画面への遷移を shift + d に変更

- .github/workflows/wc-check-diff.yaml
- .gitignore
- close #294
- 別ブランチのキャッシュが復元され、意図しない差分が出ていたため修正しました
- 検証が難しく、理論的に治りそう、といった確認のみになっています
- 再発する場合はIssueをreopenする、なども選択肢かなと思いました
> build_runnerのキャッシュをより厳密に比較するように

- packages/features/maintain/lib/src/gen/l10n/l10n.dart
- packages/features/maintain/lib/src/gen/l10n/l10n_en.dart
- packages/features/maintain/lib/src/gen/l10n/l10n_ja.dart
- packages/features/maintain/lib/src/l10n/features_maintain_en.arb
- packages/features/maintain/lib/src/l10n/features_maintain_ja.arb
- packages/features/maintain/lib/src/ui/pages/maintenance_page.dart
https://github.com/yumemi-inc/flutter-mobile-project-template/pull/317#pullrequestreview-2237058618 の指摘事項を修正した
マージンの間隔に違和感がないか
|           言語           |           Before           |           After            |
| 日本語 | <img src="https://github.com/user-attachments/assets/1fbb2e5a-026e-4e42-a777-11367be51d78" width="300" /> | <img src="https://github.com/user-attachments/assets/865836ee-db86-40b9-a47f-8435c07dda3c" width="300" /> |
| 英語 | <img src="https://github.com/user-attachments/assets/5c772fbc-b902-4e88-baae-0863e5b2b2cf" width="300" /> | <img src="https://github.com/user-attachments/assets/c20a48da-2177-4ce2-89b7-ead57c66d090" width="300" /> |
-  シミュレータの言語設定を英語/日本語と切り替えて、メンテナンスモード画面に遷移する
> [improve] fix: テキストとボタンのマージンを改行ではなくSizedBoxで表現するようにした

- packages/features/debug_mode/lib/src/ui/debug_page.dart
- packages/features/force_update/lib/force_update_status.dart
- packages/features/force_update/lib/src/model/force_update_status.dart
- packages/features/force_update/lib/src/model/force_update_target_version.dart
- packages/features/force_update/lib/src/model/force_update_target_version.freezed.dart
- packages/features/force_update/lib/src/model/version_string.dart
- packages/features/force_update/lib/src/provider/force_update_provider.dart
- packages/features/force_update/lib/src/provider/force_update_provider.g.dart
- packages/features/force_update/lib/src/provider/force_update_version_provider.dart
- packages/features/force_update/lib/src/provider/force_update_version_provider.g.dart
- packages/features/force_update/test/model/force_update_status_test.dart
- #305 
※ 引き続き対応を進めるため、敢えて close をつけていません。
強制アップデート関連処理のリファクタリングを実施します。
この PR では、以下の作業を実施しています。
- 文字列で取り扱っていたバージョン情報を VersionString に変更
- バージョンリストの取得処理を VersionString に移動
- 対象のプラットフォームからバージョン情報を取得する処理を ForceUpdateTargetVersion 内に移動
- バージョン比較の実装を VersionString に移動
- 変更に過不足がないか
- デグレ等がなさそうか
- 一旦今までの挙動と同じままになるよう、必要最低限の修正に留めています 🙏
- より良い実装方法などあればご教授いただけますと幸いです
1. エミュレータ、もしくはシミュレータにてアプリを起動
2. Shift + D でデバッグ機能から強制アップデートを有効にし、スナックバーが表示されること
> refactor(force_update): 強制アップデート関連処理のリファクタリング

- .github/workflows/initialization.yaml
- close: #326
create-issues のジョブが動作するよう修正します。
- 変更に過不足がないか
1. この PR と同様の変更内容のリポジトリを用意する
2. 1 で作成したリポジトリを利用してプライベートリポジトリを作成する
3. Initialization のワークフローが正常に動作していることを確認する
> ci: create-issues のジョブが動作するよう修正

- apps/catalog/lib/main.dart
- apps/catalog/lib/main.directories.g.dart
- apps/catalog/lib/use_case/cores/designsystem/components/progress_indicator.dart
- DeviceFrameAddonで設定されるTargetPlatfromが、MaterialThemeAddonで消えるので順番を逆にしました
| <img src="https://github.com/user-attachments/assets/18ecf4df-0ab1-4086-93de-bc4e729767a4" width="300" /> | <img src="https://github.com/user-attachments/assets/3a16e2c0-b4e9-48ab-823b-7481df6eff5b" width="300" /> | <img src="" width="300" /> |
Frameに応じたWidgetが表示されること
> chore: MaterialThemeAddonとDeviceFrameAddonを入れ替えてTargetPlatformを効かす

- .github/workflows/check-pr.yaml
resolve #292 
- 表題の通り。
- `check-pr.yaml`に`check-cycles`を追加
- https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/11852750072 で検証済
> [Improve]: CIに循環依存の検知を含める

- apps/app/lib/main.dart
> [Improve]: flutter-mobile-project-templateのライセンスをライセンス一覧で確認できるようにする #320

- packages/features/debug_mode/lib/src/ui/navigation_debug_page.dart
resolve #331 
|           Before           |           After            |
> [Improve]: DropdownMenu.expandInsets を利用して親の横幅に合わせられるようにする

- .vscode/extensions.json
- .vscode/settings.json
- apps/app/lib/l10n/app_en.arb
- apps/app/lib/l10n/app_ja.arb
- packages/features/maintain/lib/src/l10n/features_maintain_en.arb
- packages/features/maintain/lib/src/l10n/features_maintain_ja.arb
- packages/features/setting/lib/src/l10n/features_setting_en.arb
- packages/features/setting/lib/src/l10n/features_setting_ja.arb
- tools/bricks/features_package_core/__brick__/packages/features/{{feature_name.snakeCase()}}/lib/src/l10n/features_{{feature_name.snakeCase()}}_en.arb.tmp
- tools/bricks/features_package_core/__brick__/packages/features/{{feature_name.snakeCase()}}/lib/src/l10n/features_{{feature_name.snakeCase()}}_ja.arb.tmp
- tools/bricks/features_package_core/hooks/post_gen.dart
close #341 
- 追加している拡張機能に間違いないか
- 設定している項目や修正内容に誤りがないか
`mason make features_package` を実行して、期待通りに生成されることを確認しました。
> feat: google.arb-editor 拡張機能を追加

- apps/app/android/.gitignore
- apps/app/android/app/build.gradle
- apps/app/android/gradle/wrapper/gradle-wrapper.properties
- apps/app/android/settings.gradle
- #344
Android 向けのビルドが通らない状態だったため、必要な依存関係をバージョンアップしてビルドが通るようにします。
- 必要最低限の変更となっているか
- 手元でビルドが通るかご確認いただけると幸いです 🙏
- 2024/12/25 時点で最新の Android Studio Ladybug | 2024.2.1 Patch 3 で試しました
- apps/app の Android 向けビルドを実行して成功すること
> build(app): Android 向けのビルドが通るようバージョンアップ

- apps/app/ios/Podfile.lock
- apps/app/pubspec.lock
- apps/app/pubspec.yaml
- apps/website/pubspec.lock
- apps/website/pubspec.yaml
- melos.yaml
- packages/features/debug_mode/pubspec.lock
- packages/features/debug_mode/pubspec.yaml
- #344
全体的に依存ライブラリのバージョンが古くなっていたため、メジャーバージョンアップを実施します。
#345 の内容をチェリーピックすると Android はビルドできますが、iOS はまだビルドが失敗する状態です。
- 必要最低限の変更となっているか
- #345 の内容をチェリーピックしつつ Android Studio Ladybug | 2024.2.1 Patch 3 で試しました
コードベースでの確認で問題ありません。
> build(deps): 依存ライブラリのメジャーバージョンアップ

- .github/labeler.yml
- .github/labels.yml
- apps/app/pubspec.lock
- apps/app/pubspec.yaml
- apps/catalog/pubspec.lock
- apps/catalog/pubspec.yaml
- packages/cores/data/pubspec.lock
- packages/cores/data/pubspec.yaml
- packages/cores/model/.gitignore
- packages/cores/model/README.md
- packages/cores/model/analysis_options.yaml
- packages/cores/model/build.yaml
- packages/cores/model/pubspec.lock
- packages/cores/model/pubspec.yaml
- packages/cores/model/test/cores_model_test.dart
- packages/features/debug_mode/pubspec.lock
- packages/features/debug_mode/pubspec.yaml
- packages/features/force_update/pubspec.lock
- packages/features/force_update/pubspec.yaml
- packages/features/maintain/pubspec.lock
- packages/features/maintain/pubspec.yaml
- packages/features/setting/pubspec.lock
- packages/features/setting/pubspec.yaml
- packages/samples/github_repository/pubspec.lock
- samples/github_app/pubspec.lock
- #329
cores_model パッケージを追加します。
この PR ではパッケージの追加のみに留め、Issue にある cores/core からの移動については別途 PR にて対応予定です。
- 命名に違和感がないか
- 変更の過不足がないか
- この PR でのスコープはパッケージの追加のみとなっています
> feat(model): cores_model パッケージを追加

- apps/app/pubspec.lock
- apps/app/pubspec.yaml
- apps/catalog/pubspec.lock
- apps/catalog/pubspec.yaml
- apps/website/pubspec.lock
- apps/website/pubspec.yaml
- melos.yaml
- packages/cores/core/pubspec.lock
- packages/cores/core/pubspec.yaml
- packages/cores/data/pubspec.lock
- packages/cores/data/pubspec.yaml
- packages/cores/designsystem/pubspec.lock
- packages/cores/designsystem/pubspec.yaml
- packages/cores/model/pubspec.lock
- packages/cores/model/pubspec.yaml
- packages/features/debug_mode/pubspec.lock
- packages/features/debug_mode/pubspec.yaml
- packages/features/force_update/pubspec.lock
- packages/features/force_update/pubspec.yaml
- packages/features/maintain/pubspec.lock
- packages/features/maintain/pubspec.yaml
- packages/features/setting/pubspec.lock
- packages/features/setting/pubspec.yaml
- packages/samples/github_repository/pubspec.lock
- packages/samples/github_repository/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- samples/github_app/pubspec.lock
- https://github.com/yumemi-inc/flutter-mobile-project-template/issues/344
以下の PR で一度対応を行なっているが、Flutter バージョン更新後に依存ライブラリのマイナーバージョンの更新は行なっていなかったため、本 PR で実施しています。
- https://github.com/yumemi-inc/flutter-mobile-project-template/pull/347
- 必要最低限の更新対応となっているか
- ビルドができるか
メジャーバージョンの更新は別 PR で対応予定です。
> chore(deps): 依存ライブラリのマイナーバージョンアップ

- apps/app/pubspec.lock
- apps/catalog/pubspec.lock
- packages/cores/designsystem/lib/src/theme_extensions/app_colors/app_colors.g.theme.dart
- packages/cores/designsystem/pubspec.lock
- packages/cores/designsystem/pubspec.yaml
- packages/cores/ui/pubspec.lock
- packages/features/debug_mode/pubspec.lock
- packages/features/force_update/pubspec.lock
- packages/features/maintain/pubspec.lock
- packages/features/setting/pubspec.lock
- packages/samples/github_repository/pubspec.lock
- samples/github_app/pubspec.lock
- https://github.com/yumemi-inc/flutter-mobile-project-template/issues/344
以下の PR で一度対応を行なっているが、Flutter バージョン更新後に依存ライブラリのメジャーバージョンの更新は行なっていなかったため、本 PR で実施しています。
- https://github.com/yumemi-inc/flutter-mobile-project-template/pull/348
- 必要最低限の変更となっているか
- ビルドができるか
> chore(deps): 依存ライブラリのメジャーバージョンアップ

- .github/workflows/firebase-hosting-pull-request.yaml
- FirebaseExtendedがCIで失敗していたため、最新のバージョンに更新しました
- 最新のバージョンは、v0.9.0でした。
- https://github.com/FirebaseExtended/action-hosting-deploy/commits/v0.9.0/
- https://github.com/FirebaseExtended/action-hosting-deploy/tags 
- CIの失敗している内容
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/14394710572/job/40368228371
```
/usr/local/bin/npx firebase-tools@latest hosting:channel:deploy pr380-feature_378-update-y --expires 7d --project yumemi-flutter-mobile-template --json
npm warn exec The following package was not found and will be installed: firebase-tools@14.1.0
npm warn EBADENGINE Unsupported engine ***
npm warn EBADENGINE   package: 'firebase-tools@14.1.0',
npm warn EBADENGINE   required: *** node: '>=20.0.0 || >=22.0.0' ***,
npm warn EBADENGINE   current: *** node: …
```
> [381] FirebaseExtendedがCIで失敗していたため、最新のバージョンに更新しました

- apps/app/pubspec.yaml
- packages/cores/core/pubspec.yaml
- packages/cores/data/pubspec.yaml
- packages/cores/model/pubspec.yaml
- packages/features/debug_mode/pubspec.yaml
- packages/features/force_update/pubspec.yaml
- packages/features/maintain/pubspec.yaml
- packages/features/setting/pubspec.yaml
- packages/samples/github_repository/pubspec.yaml
- packages/utils/pagination/pubspec.yaml
- pubspec.yaml
- tools/bricks/brick/brick.yaml
- tools/bricks/brick/hooks/pubspec.yaml
- tools/bricks/cores_package_dart/brick.yaml
- tools/bricks/cores_package_dart/hooks/pubspec.yaml
- tools/bricks/cores_package_flutter/brick.yaml
- tools/bricks/cores_package_flutter/hooks/pubspec.yaml
- tools/bricks/features_package/brick.yaml
- tools/bricks/features_package_core/brick.yaml
- tools/bricks/features_package_core/hooks/pubspec.yaml
- tools/bricks/utils_package_flutter/brick.yaml
- tools/bricks/utils_package_flutter/hooks/pubspec.yaml
- close: #401 
- 現在ドキュメントに沿って[GET_STARTED](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/docs/ja/GET_STARTED.md) 内の `mason get` で以下のエラーが表示されます。
- [NEW_FEATURE](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/docs/ja/NEW_FEATURE.md)内の `mason make features_package` も不可
```shell
The current mason version is 0.1.1.
Because cores_package_flutter requires mason version >=0.1.0-dev.52 <0.1.0, version solving failed
```
- #383 
- 上記pipeline に合わせて `pubspec.yaml` の値を更新
- 現在のmason_cli は `0.1.2` と[pubspec.lock](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/pubspec.lock#L757-L764) 内に定義されている
- mason_cli `0.1.2`内で使用している[masonのバージョン](https://github.com/felangel/mason/blob/master/packages/mason_cli/pubspec.yaml#L19)は`0.1.0`だが**バージョ …
> fix: mason get コマンドが失敗する

- .fvmrc
- .github/actions/setup-application-runtime/action.yaml
- .gitignore
- .markdownlint-cli2.jsonc
- .vscode/settings.json
- docs/ja/GET_STARTED.md
- docs/ja/UPGRADE_FLUTTER.md
- mise.toml
- pubspec.yaml
- close: #389 
- Flutter バージョン管理を fvm から mise へ移行
- 「ツールのバージョン管理」「環境変数の切替え」「タスクランナー」を一体化し、
複数言語・複数プロジェクトを横断して 統一的な開発体験 を提供する“オールインワン開発環境マネージャー”です。
- [導入方法(別ドキュメント)](https://www.notion.so/yumemi/mise-en-place-1f1be33ee8ef80859b5af67ddfbed5b6?pvs=4)
- `mise.toml` にFlutter のバージョンを追記しました
- ドキュメントの更新を行いました
- **日本語版のみ修正しています(英語版は今後削除予定の為)**
- セットアップ
- Flutter 更新
-  fvm 関連ファイルの削除
- Github Actionsのsteps の修正
- mise が正常に動作しているかの確認をお願いします
- mise を導入し、flutter コマンドがmise 経由で使用されているかの確認をお願いします。
```shell
which flutter
```
- ローカルに作成されている …
> Improve: Flutter バージョン管理を fvm から mise へ移行

- .github/actions/create-issue-at-initialization/action.yaml
- close #417 
- 参考 PR #188
- 関連PR #415
- #415対応時にPATHを修正することを見落としていました
- `Create issues at initialization` 内のcontent-filepath を修正
|変更前|変更後|
|-- |--|
|`.github/initialization/${{ inputs.language }}/< ドキュメント名>.md`|`.github/initialization/< ドキュメント名>.md`|
- テンプレート作成時に初期Issueが自動作成されるか
- PRマージ後に新規テンプレートを作成する
Issue 自動生成に関しては、main マージ後に実際にテンプレートプロジェクト作成して issue が作成されるかを検証する必要があります。
> fix: テンプレート機能を利用した場合に GitHub に Issue が自動作成されない

- .cursorrules
close #429 
- Cursorの設定に関する変更なので、コードの動作には影響ありません
特になし
> [GH-429] chore: .cursorrulesファイルを削除

- apps/app/ios/Podfile.lock
- apps/app/pubspec.yaml
- packages/cores/core/pubspec.yaml
- packages/features/debug_mode/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- tools/diff_yaml.dart
- close: #390 
---
- `apps/app`、`packages/*`は以下に記載のあるパッケージを ルートの `pubspec.yaml` に記載しました。
- [fix: apps/app内の依存関係を pubspec.yamlに追加](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/447/commits/57d6daf44a3110cdefd462f448f3fb1bb66546fb)
- [fix: cores/core内の依存関係を pubspec.yamlに追加](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/447/commits/7380d3a66b4c914564866362103f30db2658acfb)
- [fix: cores/designsystem内の依存関係を pubspec.yamlに追加](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/447/commits/d8e770091fe3c710b9bb45209a97d16fe6797988)
- [fix: features/debug_mode内の依存関係を pubspec.yamlに追加](https://github.com/yumemi-inc/flutter-mobile-project-template/pull/447/commits/c57244b14e807777cd834e98c79e80c5e68b61b9)
- テンプレート内で既に使用していない,パッケージの削除を行いました
- …
> Improve: pubspec.yaml の dependencies の最適化

- .vscode/settings.json
> chore: settings.json に bun の設定を追加する

- packages/cores/core/lib/src/exception/app_exception.dart
- packages/features/debug_mode/lib/src/data/api/provider/exception_generator_api.dart
※ merge-queue 実行確認用の PR となるため、レビュー不要  + 直ぐにマージします
> chore: package 別変更差分あり - merge-queue  確認

- packages/cores/core/lib/src/exception/app_exception.dart
- packages/features/debug_mode/lib/src/data/api/provider/exception_generator_api.dart
※ merge-queue 実行確認用の PR となるため、レビュー不要 + すぐにマージします
> chore: package 別変更差分あり - merge-queue 確認（不要なコード削除）

- packages/cores/core/lib/src/exception/app_exception.dart
- packages/features/debug_mode/lib/src/data/api/provider/exception_generator_api.dart
- packages/features/debug_mode/lib/src/data/api/provider/exception_generator_api.g.dart
※ merge-queue 確認用の PR となるため、直ぐにマージします。レビューは不要です。
> chore: テスト用のログを追加

- packages/cores/core/lib/src/exception/app_exception.dart
> #474 Merge Queue 確認用 PR

- .husky/commit-msg
- close: #500 
- `bunx` -> `bun run` へのコマンド修正を行いました
- 
- 各コマンドの違い
- bun run
- 基本的にはプロジェクトの package.json の scripts セクションに定義されたスクリプトを実行します。
- commit lint は存在しない
- **node_modules/.bin/ ディレクトリにコマンドが存在した場合 内があったら実行する**
- bunx
- **ローカルまたはグローバルにインストールされていないパッケージのコマンド**を、その場で一時的に実行できます。
- 必要なパッケージがなければ自動でダウンロードして実行し、終了後はキャッシュされます。
> improve: bunx コマンドの削除

- .github/initialization/SPLASH_SCREEN.md
- close: #372 
- [flutter_native_splash]の設定項目が間違っている (誤: `full_screen` -> 正: `fullscreen`)
- [flutter_native_splash]の利用例 (main関数) にて、`WidgetsFlutterBinding.ensureInitialized`を再利用できていない (参考: [flutter_native_splash公式の利用例](https://pub.dev/packages/flutter_native_splash#3-set-up-app-initialization-optional))
- 上記の修正箇所が正しく修正されているか
- 上記の修正箇所そのものが正しいか、併せて他の修正箇所がないか
- 今回修正した`fullscreen`以外の[flutter_native_splash]の設定項目に問題がないこと
[flutter_native_splash]: https://pub.dev/packages/flutter_native_splash
> [372]: SPLASH_SCREEN.mdの設定とコードの例を修正

- apps/app/ios/Podfile.lock
- apps/app/pubspec.yaml
- apps/catalog/pubspec.yaml
- packages/cores/core/pubspec.yaml
- packages/cores/data/pubspec.yaml
- packages/cores/designsystem/lib/src/gen/assets/assets.gen.dart
- packages/cores/designsystem/pubspec.yaml
- packages/cores/model/pubspec.yaml
- packages/design_theme/pubspec.yaml
- packages/design_ui/lib/src/gen/assets/assets.gen.dart
- packages/design_ui/pubspec.yaml
- packages/features/debug_mode/pubspec.yaml
- packages/features/force_update/pubspec.yaml
- packages/features/maintain/pubspec.yaml
- packages/features/setting/lib/src/gen/assets/assets.gen.dart
- packages/features/setting/pubspec.yaml
- packages/infrastructure/pubspec.yaml
- packages/samples/github_repository/pubspec.yaml
- packages/utils/pagination/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- samples/webview/pubspec.yaml
- close: #465
- 関連PR: #409 
---
- Issue に自動生成されていた以下パッケージの更新を行いました
-  パッケージ値の更新
- `pubspec.yaml`
- `apps/catalog/pubspec.yaml`(例外的)
- `melos bs` の実行
| package | current | resolvable |
| :---    | :---    | :---       |
| build_runner | 2.4.14 | 2.4.15 | 
| dio | 5.7.0 | 5.8.0+1 | 
| flutter_gen_runner | 5.8.0 | 5.10.0 | 
| flutter_hooks | 0.20.5 | 0.21.2 | 
| flutter_launcher_icons | 0.14.2 | 0.14.3 | 
| go_router | 14.6.3 | 15.1.2 | 
| go_router_builder | 2.7.3 | 2.9.0 | 
| package_info_plus | 8.1.2 | 8.3.0 | 
| shared_preferences | 2.3.5 | 2.5.3 | 
| widgetbook | 3.10.2 | 3.14.1 | 
| widgetbook_annotation | 3.2.0 | 3.5.0 | 
| widgetbook_generator | 3.9.1 | 3.13.0 | 
| yumemi_lints | 3.1.0 | 4.0.0 | …
> improve: Update  package

- .cspell/ios-term.txt
- .github/actions/create-issue-at-initialization/action.yaml
- .github/initialization/TOOL_VERSION.md
- close: #511 
- 親PR: #501
---
- テンプレート使用時に自動生成されるIssueに以下を追加しました
- 重要度:  **必須**
- mise
- mise 経由
- bun
- Flutter
- dprint
- bun 経由
- cspell
- commitlint
- Husky
- その他ツール
- Xcode
- cocoapod
- Android Studio 
- プロジェクトの README.md や開発環境構築ガイドにバージョンが記載されるか
- [Issue内容](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/feature/GH-511/.github/initialization/TOOL_VERSION.md)の確認
> [自動生成Issue の追加]: 各ツールバージョン更新に関する自動Issue生成

- .github/actions/create-issue-at-initialization/action.yaml
- .github/initialization/TARGET_SDK.md
- close: #509  
- 親PR: #501
---
- テンプレート使用時に自動生成されるIssueに以下を追加しました
- 重要度:  **必須**
- Target Sdk の設定
- iOS
- Deployment Target:
- Minimum Deployments 
- Android
- targetSdkVersion
- minSdkVersion
- compileSdkVersion
- [Issue内容](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/9edc1c46a4ceca54873a6ded128196c2f7d8b4a7/.github/initialization/TARGET_SDK.md)の確認
> [自動生成Issue の追加]: TARGET SDKの自動Issue生成

- .github/actions/create-issue-at-initialization/action.yaml
- .github/initialization/ORIENTATION.md
- close: #510
- 親PR: #501
---
- テンプレート使用時に自動生成されるIssueに以下を追加しました
- 重要度:  **任意**
- 画面の向き の設定
- Dartコードによる設定
- iOSネイティブ設定
- Androidネイティブ設定
- [Issue内容](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/48d90e13ec0f5b9c4807f52d8873cf623bbbad11/.github/initialization/ORIENTATION.md)の確認
> [自動生成Issue の追加]: 画面の向きの自動Issue生成

- .cspell/ios-term.txt
- .github/actions/create-issue-at-initialization/action.yaml
- .github/initialization/LOCALIZATION.md
- close: #513 
- 親PR: #501
---
- テンプレート使用時に自動生成されるIssueに以下を追加しました
- 重要度:  **任意**
- 基本的な多言語化の方法
- 多言語化設定:
- 本来パッケージ毎に分かれていますが、分けずに基本的な方法のみを記載しています
- iOS プラットフォーム固有設定
- 動作確認
- [Issue内容](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/feature/GH-513/.github/initialization/LOCALIZATION.md)の確認
> [自動生成Issue の追加]: 多言語化に関する自動Issue生成

- apps/app/android/app/build.gradle.kts
- close: #528 
- [apps/app/android/app/build.gradle.kts](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/apps/app/android/app/build.gradle.kts)の`compileSdkVersion`を`flutter.compileSdkVersion`に変更
- 上記Issueに記載の **Flutter で利用しているバージョン** である35に更新して、ビルド時のエラーを解決するべき
- 現状、固定値を使用する必要はないと判断して、`flutter.compileSdkVersion`を用いるように変更しました
- `compileSdk = 35`ではなく、`compileSdk = flutter.compileSdkVersion`にする
- [.github/initializations/TARGET_SDK.md](https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/.github/initialization/TARGET_SDK.md) の変更は行なっていません
- 上記の判断について、認識いかがでしょうか?
| <img src="" …
> [528]: compileSdkVersionをflutterの設定に変更

- .github/initialization/TARGET_SDK.md
- close: #530 
- 修正内容
- GradleファイルをGroovyからKotlin DSLに移行
- サンプルコードおよび`FlutterExtension`クラスの内容とパスを移行
- 現在使用していないmarkdownlint関連の内容を削除
- 修正内容に問題がないか
- `FlutterExtension`の内容とパスがFlutter v3.32.0のものかどうか
> [530]: `TARGET_SDK.md`の情報を更新し、Gradleファイルの記述を修正

- .github/workflows/check-pr.yaml
- .github/workflows/initialization.yaml
- .github/workflows/merge-queue.yaml
- .github/workflows/wc-check-diff.yaml
一部yamlで`actions/checkout`が`v4.1.1`を使用しているが、基本的に`v.4.1.7`を使用している。
そのため、`v4.1.1`を呼び出している箇所を`v4.1.7`に書き換え。
- 変更したyamlファイルの`checkout`actionが正常に動いているか
N/A
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/15431738415/job/43430732949?pr=541
上記実行履歴より、
- .github/workflows/check-pr.yaml
- .github/workflows/wc-check-diff.yaml
が正常に実行完了し`v4.1.7`の`actions/checkout`が動くことを確認。
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/15431738415/job/43430732949?pr=541
上記URLにアクセスし、`Re-run all jobs`を実行。
N/A
> actions/checkout をv4.1.1からv4.1.7にマイグレート

- apps/app/pubspec.yaml
- packages/debug/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- samples/webview/pubspec.yaml
- https://github.com/yumemi-inc/flutter-mobile-project-template/issues/551#issuecomment-3240653939 のロギング & lint 系対応
- ビルドが成功するか
- CI が通っているか
- iOS/Android でビルドを行う
> chore: パッケージの更新（logging & lint）

- docs/ARCHITECTURE.md
- close: #471
GitHub Issue #471 の要求に従い、`ARCHITECTURE.md` にアーキテクチャの詳細説明を追加しました。Clean Architecture と Composition Root パターンを組み合わせたアーキテクチャの設計思想、実装パターン、各レイヤーの責務について包括的に説明しています。
- アーキテクチャの説明が適切で分かりやすいか
- 実装例が実際のプロジェクトコードと一致しているか
- Mermaid 図の依存関係が正しく表現されているか
- エラーハンドリングの方針が実用的か
1. `docs/ARCHITECTURE.md` を開いて内容を確認する
2. Mermaid 図が正しく表示されることを確認する
3. 実装例のコードが適切にハイライトされることを確認する
- 実装例は実際のプロジェクトコード（`theme_setting` 関連）を参考に作成
- エラーハンドリングの方針は基本的な方針のみを記載し、詳細はプロジェクトごとの検討に委ねる設計
- アーキテクチャの純粋性と実装コストのバランスを考慮した実用的なガイダンスを提供
> docs: アーキテクチャの詳細説明を追加
