yumemi-inc/flutter-mobile-project-template

apps/app/lib/data/provider/github_access_token.dart, apps/app/lib/data/provider/github_access_token.g.dart
表題の問題があったため、処理を修正
- アクセストークンの指定がない場合に通信ができる
- リクエストのヘッダを追加しない
- アクセストークンの指定がある場合に通信ができる
1. 起動時にアクセストークン（`GITHUB_ACCESS_TOKEN`）を指定(する|しない)
2. 起動し、通信が成功することを確認する
=> アクセストークンの指定がない場合に通信失敗する問題の修正

melos.yaml
close #87 
- 依存関係に応じて、`melos run regenerate_code` が実行されているかを確認する
ローカルで実行時のログ
```bash
melos run regenerate_code
└> melos exec -- "dart run build_runner build -d"
└> RUNNING
$ melos exec
└> dart run build_runner build -d
└> RUNNING (in 4 packages)
--------------------------------------------------------------------------------
[cores_data]: [INFO] Generating build script...
[features_debug_mode]: [INFO] Generating build script...
[features_github_repository]: [INFO] Generating build script...
[flutter_app]: [INFO] Generating build script...
[cores_data]: [INFO] Generating build script completed, took 170ms
[cores_data]: 
[features_debug_mode]: [INFO] Generating build script completed, took 171ms
[features_debug_mode]: 
[features_github_repository]: [INFO] Generating build script completed, …
```
=> feat: melos exec コマンドがパッケージ間の依存関係に応じて実行される設定を追加する

.github/workflows/auto-assign.yaml
- close: #128 
- チームがレビュアーに自動で設定されるか
- アサインには、変わらずプルリクエスト作成者が設定されるか
※ 見た目の変更がないため省略
GitHub Actions のワークフローの実行結果を確認する。
📝 いったん↓のように変更して挙動確認しています。（現在は元に戻しています。）
↓ Draft でプルリクエスト作成時
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/7888068571
↓ Draft のプルリクエストで ready for review を押下時
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/7888088807/job/21524769718?pr=132
- 動作確認のため、一度自動的に Kotaro666-dev さんがレビュアーに設定されましたが、↓のプルリクエストの続きということで、 @iseruuuuu さんと @tatsutakein さんにレビュー依頼し直しました。
- https://github.com/yumemi-inc/flutter-mobile-project-template/pull/129
- マージ後にリポジトリの変数として定義していた `REVIEWERS` は削除予定
=> ci: レビュアーにチームを指定するように変更

.github/actions/setup-application-runtime/action.yaml
`subosito/flutter-action` のキャッシュが悪さをしていた？ようでしたので、最新の v2.14.0 に更新しました。
↓の Dart の pub cache のライフサイクルと作成場所がおかしくなっていそうでした。
https://github.com/subosito/flutter-action/compare/v2.12.0...v2.13.0
v2.13.0 で不具合は解消されたようですが、別の改善点があったようでしたので v2.14.0 に更新しました。
- v2.14.0
- https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/8372609664/job/22923914440?pr=168
- v2.13.0 にダウングレードすると成功
- https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/8372626349/job/22923967304?pr=168
- v2.12.0 にダウングレードすると失敗
- https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/8372772382/job/22924416504?pr=168
- 認識おかしくないか
なし
なし
=> `subosito/flutter-action` を最新バージョンに更新

.github/workflows/check-pr.yaml
#191
根本的な対応は、時間のかかっているステップの時間をどうにか短くしないといけないため、クローズはしません。
ついでに pre-check ジョブのタイムアウト時間を念の為設定しておきました。
- 設定値は妥当か
- 設定のミスはないか
特になし
=> ci: check-pr ワークフローがタイムアウトで失敗しないように一時的な対応

.github/actions/setup-application-runtime/action.yaml, .github/workflows/check-pr.yaml, .github/workflows/wc-changes.yml, .github/workflows/wc-check-diff.yaml
- close: #224
GitHub Actions でキャッシュを利用するよう改善します．
- キャッシュ用のジョブ ( cache-dependencies ) を挟むことで他のジョブ ( check, lint, diff-gen ) は高速化されていますが，トータルでみると少し遅くなったように感じます
- 今後他にも並列で走らせたいものが増える場合や，コード量が増える場合はこの構成が有効そうです
- 逆に今の規模からコード量が増えないのであればあまり効果がないように思えます
- コードに違和感がないか
- CI が流れる状態となっているか（デグレしていないか）
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/9378775404
<details>
<summary>独自で actions/cache を併用した場合</summary>
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/9378814404/attempts/1
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/9378814404
</details>
=> [GH-224] GitHub Actions でキャッシュを利用するよう改善

.github/labeler.yml, .github/labels.yml, .github/workflows/labeler.yml, .github/workflows/labels.yml
ラベルの管理と紐づけをワークフロー化します．
現状パッケージラベルが手動での管理となるため，自動生成の Issue (#244) を作成しています．
- ラベルに過不足がなさそうか
以下の実行結果をご確認ください 🙏
https://github.com/yumemi-inc/flutter-mobile-project-template/actions/runs/9394833581/job/25873179634?pr=243
=> [GH-237] ラベルの管理と紐づけをワークフロー化

packages/cores/core/lib/src/app_status/provider/app_status_provider.dart, packages/cores/core/lib/src/app_status/provider/app_status_provider.g.dart
#245 の作り直し。
`appStatus` provider において、 `MaintenanceModeStatus` と `ForceUpdateStatus` の不要なインスタンス再生成があったので修正しました。
インスタンス生成のオーバーヘッドやメモリ使用量の増大はわずかだと思いますが、都度生成していると今後 `MaintenanceModeStatus` や `ForceUpdateStatus` に、メンバーの追加があるがコンストラクタでデフォルト値が設定されているという場合に古い値が無視されてしまうことが懸念されます。
- インスタンスを再生成していた特別な理由が無いか
この変更後にメンテナンスモードと強制アップデートの状態変更が監視できているのは確認しました。
<video width=300 src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/31601805/c7233a9b-c204-4a49-bb05-5885992376ad">
=> Refactor AppStatus provider to use existing state instances directly

packages/features/setting/pubspec.yaml
たまたま見つけた軽微な修正のため、Issue の作成はスキップしてそのまま PR 作成しました。
```diff
-    path: ../../../packages/cores/core
+    path: ../../cores/core
```
上記のような参照 path を修正しています。
動作には変更がないリファクタリングになります。
- CI 🟢 
省略
CI 🟢
=> pubspec.yaml においてローカルパッケージへの参照部分で戻り過ぎていた階層を修正

.github/initialization/RENAME_APPLICATION_ID.md, apps/app/android/app/build.gradle, apps/app/flavor/dev.json, apps/app/flavor/prd.json, apps/app/flavor/stg.json, apps/app/ios/Runner.xcodeproj/project.pbxproj, tools/rename-application-id.sh
resolve #257 
設定をまとめたファイルを作ってパースさせる案もあったが、一回限りのスクリプトに割くには見合っていないということで最小限の変更で対応。
#203 の対応時にあらためて検討されたい。
- 実行後の変更箇所・変更内容に過不足がないか
<details><summary><b>参考: 修正前の実行後</b></summary><div>
```diff
diff --git a/apps/app/android/app/src/main/kotlin/jp/co/yumemi/flutter_app/MainActivity.kt b/apps/app/android/app/src/main/kotlin/jp/co/yumemi/flutter_app/MainActivity.kt
deleted file mode 100644
index ccc7325..0000000
--- a/apps/app/android/app/src/main/kotlin/jp/co/yumemi/flutter_app/MainActivity.kt
+++ /dev/null
@@ -1,5 +0,0 @@
-package jp.co.yumemi.flutter_app
-
-import io.flutter.embedding.android.FlutterActivity
-
-class MainActivity: FlutterActivity()
diff --git a/apps/app/flavor/dev.json b/apps/app/flavor/dev.json
index 5ba9ec3..bf98f95 100644
--- a/apps/app/flavor/dev.json
+++ …
```
=> [GH-257] Android Application ID と iOS Bundle ID を別々にリネームできるようにする

apps/app/lib/router/provider/router.g.dart, apps/app/lib/router/routes/main/home/debug_page_route.dart, apps/app/lib/router/routes/main/home/home_shell_branch.dart, melos.yaml, packages/features/debug_mode/lib/src/ui/debug_page.dart, packages/features/debug_mode/lib/src/ui/navigation_debug_page.dart, packages/features/debug_mode/lib/src/ui/provider/navigator_provider.dart, packages/features/debug_mode/lib/src/ui/provider/navigator_provider.g.dart, packages/features/debug_mode/lib/ui.dart, packages/features/debug_mode/pubspec.lock, packages/features/debug_mode/pubspec.yaml
close: #235
- こちらをベースに一部バグを修正しています
https://github.com/FlutterKaigi/2024/pull/120
- 元Issueの「デバッグ時のみ」をどう実現するのが良さそうかは別途考える必要がありそうなので、このPRではやってません。（遷移元のボタンを消す？）
|           デバッグ画面           |           ナビゲーションデバッグ画面            |
| <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/90010509/9c2cf03c-9b4e-4ea0-af89-88c4d20f6253" width="300" /> | <img src="https://github.com/yumemi-inc/flutter-mobile-project-template/assets/90010509/83d77a77-2774-4c1a-a6e4-fcfcd7c90579" width="300" /> |
- 画像のデバッグ画面から、ナビゲーションデバッグ画面へ遷移
- ドロップダウンで遷移したい画面を選択
このPRでやれてないことをIssue化
#267 
#268
=> デバッグ時に、任意の画面にすぐ遷移できるようにする

pubspec.lock, pubspec.yaml, tools/gen_labeler.dart, tools/gen_labels.dart, tools/utils/command_runner.dart, tools/utils/label.dart, tools/utils/logger.dart, tools/utils/melos.dart, tools/utils/path.dart
- close: #290
grinder とほぼ同じような処理に実装していますが、使っていない部分は実装していません。
- 独自実装した処理は問題ないか
- `melos bs` で labeler.yml, labels.yml が期待通りに生成されるか
=> improve: grinder を利用していた処理を独自実装して差し替え

apps/website/pubspec.lock, apps/website/pubspec.yaml
チケットはありません。
website で Flutter のバージョンを指定していなかったため、 `melos bs` コマンドでエラーが発生してしまっていました。
```shell
--------------------------------------------------------------------------------------------------------------------------
[website]: Please put [flutter: Flutter Version] under the environment section in pubspec.yaml
--------------------------------------------------------------------------------------------------------------------------
$ melos exec
└> dart run yumemi_lints update
└> FAILED (in 1 packages)
└> website (with exit code 1)
melos run yumemi_lints_update
└> melos exec -- "dart run yumemi_lints update"
└> FAILED
ERROR: ERROR: ScriptException: The script yumemi_lints_update failed to execute.
```
- `melos bs` コマンドを実行してエラーが発生しないか
特になし
=> fix: website でも Flutter のバージョンを指定

apps/catalog/lib/main.dart
resolve #291 
- `context`や`child`へのアクセスを行ってもWidgetbookの内部実装による影響を受けてしまうため、
Elementを走査する形での対応となった
- メンテナンスの観点から問題ないか
TextListTile|CircularProgressIndicator|Scaffoldあり
--|--|--
=> [Bug]: catalogのBuilderAddonの挙動が想定通りでない

.github/workflows/check-pr.yaml, .github/workflows/wc-check-diff.yaml, docs/ja/NEW_FEATURE.md, melos.yaml
- close: #352
melos.yaml のスクリプトの命名を簡潔でわかりやすくなるよう変更します。
- 命名に違和感がないか
- 変更の過不足がないか
- この PR でのスコープは命名変更のみとして、内容のカイゼン(stepsへの変更など)は実施しない想定です
=> ci(melos): スクリプトの命名変更

.gitignore, .idea/jsonSchemas.xml
- close: #309
#335 にて VSCode では melos.yaml のスキーマが参照できるようになりましたが、IntelliJ 系の IDE に対しては適用されていませんでした。
この PR では、IntelliJ 系の IDE に対しても melos.yaml のスキーマが参照できるようにします。
- 変更内容に過不足がないか
- IntelliJ 系の IDE で melos.yaml のスキーマが参照できているか
https://github.com/user-attachments/assets/b0240280-8427-475d-893c-d01a927f86d2
=> chore: intelliJ 系の IDE に対して melos.yaml のスキーマが参照できるよう変更

packages/features/webview/lib/src/ui/web_page.dart
- close: #162 
- close: #163  
オフライン⇨オンラインに切り替わる際、WebViewが再作成される不具合が存在していた。
本問題はオフライン時に`Visibility`が`WebView`のレンダリング情報を削除したことが起因し、`WebView`が再作成されていた。
そのため、`Visibility`を`Visibility.maintain`に修正し、レンダリング情報が保持されるようにした。
|           iOS           |           Android            | 
| <video src="https://github.com/user-attachments/assets/38ec348d-8ae4-4ddc-9ffe-f5f7d7de6686" width="300">  | <video src="https://github.com/user-attachments/assets/b5096162-4827-4614-958c-4eb95e5dbd10" width="300" /> |
1. オンライン上でpull to refreshを実行し、画面が正常に更新されること
2. オフライン上でpull to refreshを実行し、エラー画面が表示されること
3. オフライン⇨オンラインに変更し、pull to refreshを実行し、画面が正常に更新されること
上記1~3を順に試しました。
1. `dev-debug` を実行する
2. WebViewで特定の画面を開く
3. Wi-Fiをオフに変更し、検証機をオフライン状態にする
4. pull to …
=> [162] オフライン⇨オンラインに戻る時のWebViewを再作成しないように修正

packages/domain_logic/.gitignore, packages/domain_logic/lib/internal_domain_logic.dart, packages/domain_logic/lib/src/theme_mode/theme_mode_repository.dart, packages/domain_logic/pubspec.yaml, packages/infrastructure/.gitignore, packages/infrastructure/lib/internal_infrastructure.dart, packages/infrastructure/lib/src/shared_preferences/shared_preference_data_source.dart, packages/infrastructure/lib/src/shared_preferences/shared_preferences_keys.dart, packages/infrastructure/lib/src/theme_mode/theme_mode_repository_impl.dart, packages/infrastructure/pubspec.yaml
close: #441
テーマモード（ライト/ダーク/システム）の管理機能を実装しました。
SharedPreferencesを使用してユーザーのテーマ設定を永続化し、アプリ起動時に設定を復元できるようになります。
- Domain Logic層とInfrastructure層の責務分離が適切に行われているか
- SharedPreferencesを使用したデータ永続化の実装が適切か
- ThemeModeRepositoryのインターフェース設計が適切か
- エラーハンドリングが適切に実装されているか
=> [GH-441] infrastructureパッケージへの切り出し

packages/domain_model/build.yaml, packages/domain_model/lib/internal_domain_model.dart, packages/domain_model/lib/src/force_update_settings_state.dart, packages/domain_model/lib/src/force_update_settings_state.freezed.dart, packages/domain_model/lib/src/force_update_target_version.dart, packages/domain_model/lib/src/force_update_target_version.freezed.dart, packages/domain_model/lib/src/maintenance_mode_settings_state.dart, packages/domain_model/lib/src/maintenance_mode_settings_state.freezed.dart, packages/domain_model/lib/src/version_string.dart, packages/domain_model/pubspec.yaml
close: #439
アプリの強制アップデートとメンテナンスモード機能に必要なドメインモデルを追加しました。
主な追加項目：
- `ForceUpdateSettingsState` - 強制アップデート設定の状態管理
- `ForceUpdateTargetVersion` - 強制アップデート対象バージョンの管理
- `MaintenanceModeSettingsState` - メンテナンスモード設定の状態管理  
- `VersionString` - バージョン文字列の比較機能付きextension type
- ドメインモデルの設計が適切かどうか
- 強制アップデート判定ロジック（`ForceUpdateSettingsState.isForceUpdateEnabled`）の妥当性
- `VersionString`のバージョン比較演算子の実装
- Freezedの使用方法とビルド設定
このPRではドメインモデルの追加のみで、実際の機能実装は別PRで行います。
=> [GH-439] domain_model に移行

apps/app/ios/Podfile.lock, packages/debug/lib/src/ui/shake_detection.dart, packages/debug/pubspec.yaml, pubspec.lock
shake パッケージだと、iOS Simulator での Shake に反応しないため shake_gesture パッケージに置き換えました。shake_gesture パッケージはより軽量で効率的な shake 検出を提供し、コードの簡素化も実現できます。
- shake_gesture パッケージへの置き換えが適切に行われているか
- 実装の簡素化（StatefulWidget から StatelessWidget への変更）が適切か
- 依存関係の更新が正しく行われているか
動作確認できました！
https://github.com/user-attachments/assets/506f5f09-7355-4623-8f75-3cb79bc7f2fc
1. アプリを起動する
2. デバッグモードで shake 検出が正常に動作することを確認する
- shake_gesture パッケージは shake パッケージよりも軽量で、パフォーマンスが向上します
- StatefulWidget から StatelessWidget への変更により、コードがより簡潔になりました
=> refactor: shakeパッケージをshake_gestureパッケージに置き換え
